language: c

cache: apt

dist: trusty

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc

script:
  - make

addons:
  apt:
    packages: libhidapi-dev
  homebrew:
    packages: hidapi
    update: true
